nameOverride: ""
fullnameOverride: ""
plugin:
  enabled: true
  versionOverride: ""
  noCache: false
  noAuth: false
  metadata:
    catalog.cattle.io/rancher-version: ">= 2.9.0-0 < 2.10.0-0"
    catalog.cattle.io/ui-extensions-version: ">= 2.0.1 < 3.0.0"
