name: Build and Release Extension Charts

on:
  workflow_dispatch:
    inputs:
      target_branch:
        required: true
        type: string
        description: "target_branch"
      tagged_release:
        required: true
        type: string
        description: "tagged_release"
      is_test:
        required: false
        type: string
        description: "is_test"
      test_ext_repo:
        required: false
        type: string
        description: "test_ext_repo"
      test_ext_branch:
        required: false
        type: string
        description: "test_ext_branch"

env:
  ACTIONS_RUNNER_DEBUG: false
  CI_COMMIT_MESSAGE: CI Build Artifacts

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  build-extension-artifact:
    name: Build extension artifact
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    outputs:
      build-status: ${{ job.status }}
    steps:
      - if: inputs.is_test == 'true'
        name: Checkout (test flow)
        uses: actions/checkout@v4
        with:
          repository: rancher/${{ inputs.test_ext_repo }}
          ref: ${{ inputs.test_ext_branch }}
          fetch-depth: 0
      
      - if: inputs.is_test != 'true'
        name: Checkout (normal flow)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Enable Corepack
        run: corepack enable

      - name: Configure Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.0

      - name: Setup Nodejs with yarn caching
        uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: yarn

      - name: Parse Extension Name
        id: parsed-name
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          yarn parse-tag-name ${{ inputs.tagged_release }} ${{ github.run_id }} "charts"

      - name: Run build script
        shell: bash
        id: build_script
        run: |
          publish="yarn publish-pkgs -s ${{ github.repository }} -b ${{ inputs.target_branch }}"

          if [[ -n "${{ inputs.tagged_release }}" ]]; then
            publish="$publish -t ${{ inputs.tagged_release }}"
          fi

          if [[ "${{ inputs.is_test }}" == "true" ]]; then
            publish="$publish -f"
          fi

          $publish

      - name: Upload charts artifact
        uses: actions/upload-artifact@v4
        with:
          name: charts
          path: tmp

  release:
    name: Release Build
    needs: build-extension-artifact
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      deployments: write
      pages: write
    outputs:
      release-status: ${{ job.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: '${{ inputs.target_branch }}'

      - name: Configure Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: charts

      - name: Commit build
        run: |
          git add ./{assets,charts,extensions,index.yaml}
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: ./charts/*
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          CR_SKIP_EXISTING: true
